### PR TITLE
Mark processed sets for curation

### LINKED ISSUE #113: Unknown population name in processed_trait_datasets
The `population_id` column in `processed_trait_datasets` has only two distinct values:
  - `BnaTNDH_00` (this is a known population)
  - `BolAGDH_05` (no such population exists, although B. oleracea AGDH populations with lower numbers - up to 04 - are known).

What should we do about the latter record?

### PR DESCRIPTION
**Pull request by nowakowski**
Fixes #113

### CODE REVIEW

**Comment by nowakowski** [comment]
Well, *kinda* fixes - adds comments requesting dataset owner's attention.

**Comment by nowakowski** [comment]
Now also fixes #157

**Comment by Nuanda** [comment]
:+1:

**Comment by Nuanda** [comment]
@nowakowski Piotr, I still find `plant_population_id` in the `processed_trait_datasets` table in `schema.rb`. It's also present in Postgres DB.

Shouldn't that be removed?

**Pull request merged**
