### PR TITLE
Makes "Related" counters updated by number of invisible records

### LINKED ISSUE #456: Manage counters of related models to include/exclude private relations

### PR DESCRIPTION
**Pull request by Nuanda**
Fixes #456 

The visibility of the related records depends on the usual algorithm. Counters should be updated correctly.

### CODE REVIEW

**Comment by Nuanda** [comment]
One quite minor thing is with PP - PPL - PL relation. If a PP has a public PPL, that has a private PL, the counter on PP will still show 1 (though navigating there will result in an empty table, so no privacy break there). I'm afraid fixing that single case would be quite difficult so I do not intend to do that, unless some simple fix is found (or more cases like that will appear after model changes).

Also, please remember to deactivate DTController cache before testing, as #390 is still open.

**Comment by kammerer** [comment]
:+1: 

Seems to work OK. Not the easiest thing to read, not that I have any idea how to improve it.

As for PP - PPL - PL relation, I think we can add a callback to PL changing PPL visibility according to PL's visibility. It should be safe to do that both ways.

**Comment by Nuanda** [comment]
Did you mean something like that?

**Comment by kammerer** [comment]
Yup

2016-04-18 23:14 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Did you mean something like that?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/468#issuecomment-211581982>
>



-- 
Tomasz Szymczyszyn

**Pull request merged**
