### PR TITLE
script to detect unused tables (empty or with meaningless data) and to drop them

### LINKED ISSUE #52: Remove unused data tables from the crop store schema
This should help us with tackling the complexity of the old data model. We should remove all tables (and references to those tables) that have no meaningful data. My simple check shown the following cases (I list table_name.primary_key_name: all distinct PK values):
 - clone_libraries.library_name: ["unspecified", "not applicable", "none"]
 - marker_sequence_hits.canonical_marker_name: ["unspecified", "not applicable", "none"]
 - row_plot_positions.row_plot_position_id: ["unspecified", "not applicable", "none"]
 - plant_line_assigned_genotypes.plant_line_name: ["unspecified", "not applicable", "none"]
 - plant_trial_collection_lists.plant_trial_collection_id: ["unspecified", "not applicable", "none"]
 - population_locus_alleles.plant_population: ["unspecified", "not applicable", "none"]
 - pop_locus_genotype_alleles.plant_population: ["unspecified", "not applicable", "none"]
 - plant_marker_fragments.scoring_unit_id: ["unspecified", "not applicable", "none"]
 - marker_variations.marker_variation: ["unspecified", "not applicable", "none"]
 - plant_individuals.plant_individual_id: ["unspecified", "not applicable", "none"]
 - clones.clone_name: ["unspecified", "not applicable", "none"]
 - plant_marker_variations.scoring_unit_id: ["unspecified", "not applicable", "none"]
 - plant_trial_collections.plant_trial_collection_id: ["unspecified", "not applicable", "none"]
 - population_genotypes.plant_population: ["unspecified", "not applicable", "none"]
 - cs_synonyms.cs_synonym_id: ["none", "unspecified"]
 - cs_images.cs_image_id: ["none", "unspecified"]
 - cs_images_lookup.cs_image_id: ["none", "unspecified"]
 - cs_additional_information.table_name: ["none", "unspecified"]
 - cs_publications.cs_publication_id: []
 - cs_people.cs_person_id: []
 - proccessed_trait_datasets.proccessed_trait_dataset_id: []
 - cs_institutions.cs_institution_id: []
 - cs_publications_lookup.cs_publication_id: []

It's a lot of unnecessary complexity and removing it should help.

@nowakowski I already work on a solution to this so tell me if you want to get involved.

### LINKED ISSUE #56: Remove unused data columns from existing crop store schema tables
I wrote simple check for all CS schema tables (less the ones we plan to drop anyway: #52) to see what columns have only meaningless values and, possibly, could be safely removed. Here are the results:

- Table genotype_matrices:
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table marker_assays:
  * Column restriction_enzyme_a has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column restriction_enzyme_b has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column reanneal_temp has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column sequence_confirmed_by_whom has only meaningless values: ["unspecified", "not applicable", "none"].
- Table marker_sequence_assignments:
  * Column described_by_whom has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table plant_accessions:
  * Column ownership has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column pollination_method has only meaningless values: ["unspecified", "not applicable", "none"].
- Table plant_scoring_units:
  * Column seed_packet_id has only meaningless values: ["unspecified"].
- Table plant_varieties:
  * Column taxa_authority has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column subtaxa_authority has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column data_owned_by has only meaningless values: ["unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table plant_variety_detail:
  * Column breeder has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column agent has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column data_owned_by has only meaningless values: ["unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table population_loci:
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "not applicable", "none"].
- Table primers:
  * Column design_seq_id has only meaningless values: ["not applicable", "unspecified", "none"].
  * Column design_seq_source_acronym has only meaningless values: ["not applicable", "unspecified", "none"].
  * Column reanneal_temp has only meaningless values: ["not applicable", "", "none", "unspecified"].
  * Column designed_by_whom has only meaningless values: ["not applicable", "unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table probes:
  * Column pcr_primer_name_a has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column pcr_primer_name_b has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column forward_position has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column reverse_position has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column template_source has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column preparation_description has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column prepared_by_whom has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column probe_length has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column gene_description has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column data_owned_by has only meaningless values: ["unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table processed_trait_datasets:
  * Column raw_dataset_id has only meaningless values: ["unspecified"].
  * Column raw_dataset_analysis_occasion has only meaningless values: ["unspecified"].
  * Column stats_analysis_description has only meaningless values: ["unspecified"].
  * Column trait_mean has only meaningless values: ["unspecified"].
  * Column trait_total_variance has only meaningless values: ["unspecified"].
  * Column additive_genetic_variance has only meaningless values: ["unspecified"].
  * Column residual_variance has only meaningless values: ["unspecified"].
  * Column average_sed has only meaningless values: ["unspecified"].
  * Column line_mean_type has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table qtl:
  * Column se_additive_effect has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table qtl_jobs:
  * Column qtl_parameters has only meaningless values: ["unspecified"].
  * Column threshold_significance_level has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table scoring_occasions:
  * Column scored_by_whom has only meaningless values: ["not applicable", "none", "unspecified"].
  * Column recorded_by_whom has only meaningless values: ["not applicable", "none", "unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["none", "unspecified"].
- Table trait_grades:
  * Column described_by_whom has only meaningless values: ["not applicable", "none", "unspecified"].
  * Column data_owned_by has only meaningless values: ["none", "unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["none", "unspecified"].
- Table trait_scores:
  * Column spread_type has only meaningless values: ["unspecified", "not applicable"].

@nowakowski tell me what you think.

### PR DESCRIPTION
**Pull request by Nuanda**
Fixes #52 
Fixes #56 

@nowakowski please take a look. It's a simple check - but I also checked that manually in psql and there really is no useful data in these tables. Better to be executed before our migrations (not to drop some needed table from the new bip model).

### CODE REVIEW

**Comment by Nuanda** [comment]
Final task added - it removes all blank records from all existing tables (by `blank record` I understand any record that has 'blank' values for all of its PKeys). Afterwards it performs a heavy task of replacing all blank values of all columns in the given table with NULLs. Where applicable, it drops NOT NULL constraint to be able to do so.

There are two outstanding cases where this does not work: `map_positions` and `map_locus_hits` (column `map_position` in both cases) - that is because that column contains 'unspecified' values (23 and 28 records, respectively), but it's a PKey and Postgres does not allow me to drop the NOT NULL restriction for that column. Can we remove it from the PKey array for those tables?

**Comment by Nuanda** [comment]
Current purgatory tasks include, in that order:
- rake curate:purge_empty_tables
- rake curate:purge_empty_columns
- rake curate:purge_placeholder_records

They should be run after loading the psql dump but *before* creating the `migrations` table.

**Comment by Nuanda** [comment]
@nowakowski ready for your review - please double check if all these removals are ok.

**Comment by Nuanda** [comment]
Ok, hopefully this is the last commit here. I took some time to adjust cs migration to reflect the dropped 'not nulls' and 'defaults'.

Surely, with respect to defaults and not nulls, much more work is needed, as discussed in some other tasks.

**Comment by nowakowski** [comment]
OK, I've gone through the whole procedure and it seems to work. :+1:

**Pull request merged**
