### PR TITLE
Preliminary design of the user data submission workflow/process

### PR DESCRIPTION
**Pull request by kammerer**
It requires more work to be sure but you may take a look and tell what do you think.

I decided to store submission data as a JSON document for now but this solution can be easily adopted if we change it to relational data in the future.

### CODE REVIEW

**Comment by Nuanda** [comment]
Looks rather ok to me. Hasn't made a code review, since I presume this branch is not ready for that yet, but overall the approach looks good. One problem is with strong parameters - I wrote it down in a separate comment.

You may take this branch and start to adjust this generic submission model to the concrete case of user's plan population submission we have talked over in email.

**Comment by kammerer** [comment]
Tomasz, can you take a peek at the submission process and tell if this is the right direction? Any input is welcome. Of course I am aware of many shortcomings such as:

* clumsy wording
* [step 2] validation issue allowing to select TT / PL and add a new one at the same time
* [step 2] TT / PL inputs not show immediatelly when there are validation errors
* view showing complete submission not listing any useful information

Please, do not bother looking at the code at the moment, it is not up to it yet.

**Comment by Nuanda** [comment]
First thing I spotted that there might be sth wrong with memory management. When I go to http://127.0.0.1:3000/submissions/ it takes up ~77 MB (as seen in Chromium process list). When I simply click on "Submit new research data" it grows to ~110 MB. Few click there and it's as high as 155 MB... I didn't use the autocomplete yet.

Do you think it's a turbolinks problem of not having the entire page refreshed?

**Comment by kammerer** [comment]
We do not use turbolinks

2015-02-27 11:53 GMT+01:00 Tomasz Gubała <notifications@github.com>:

> First thing I spotted that there might be sth wrong with memory
> management. When I go to http://127.0.0.1:3000/submissions/ it takes up
> ~77 MB (as seen in Chromium process list). When I simply click on "Submit
> new research data" it grows to ~110 MB. Few click there and it's as high as
> 155 MB... I didn't use the autocomplete yet.
>
> Do you think it's a turbolinks problem of not having the entire page
> refreshed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/11#issuecomment-76375932>.
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
Exactly, I have just confirmed that as well. So, I don't think a 3-field form should take as much memory...

**Comment by Nuanda** [comment]
Apart from the memory issue I'd say it is the right direction. I can see this PR as a basis for further work, but I'm not sure if we should dive into that right away. It is up to you but I myself would prefer to have this code tidied up, reviewed and merged with master before doing any further work.

Then we can split further work into a series of tasks. The biggest will probably be a proper support for PlantPopulationLists.

BTW does it populate the PP/PL tables when submitted or not yet?

**Comment by kammerer** [comment]
As for now it only saves collected input in Submission#content

2015-02-27 12:22 GMT+01:00 Tomasz Gubała <notifications@github.com>:

> Apart from the memory issue I'd say it is the right direction. I can see
> this PR as a basis for further work, but I'm not sure if we should dive
> into that right away. It is up to you but I myself would prefer to have
> this code tidied up, reviewed and merged with master before doing any
> further work.
>
> Then we can split further work into a series of tasks. The biggest will
> probably be a proper support for PlantPopulationLists.
>
> BTW does it populate the PP/PL tables when submitted or not yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/11#issuecomment-76380237>.
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
That is good - since we will have to solve several issues with the correct Plant* model for BIP.

**Comment by kammerer** [comment]
Ok, in the next steps I will then investigate memory issue and tidy up the
code so that it can be merge do master.


2015-02-27 12:22 GMT+01:00 Tomasz Gubała <notifications@github.com>:

> Apart from the memory issue I'd say it is the right direction. I can see
> this PR as a basis for further work, but I'm not sure if we should dive
> into that right away. It is up to you but I myself would prefer to have
> this code tidied up, reviewed and merged with master before doing any
> further work.
>
> Then we can split further work into a series of tasks. The biggest will
> probably be a proper support for PlantPopulationLists.
>
> BTW does it populate the PP/PL tables when submitted or not yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/11#issuecomment-76380237>.
>



-- 
Tomasz Szymczyszyn

**Comment by kammerer** [comment]
@Nuanda I have not noticed increased memory consumption using Chromium Version 40.0.2214.111 Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit)

**Comment by Nuanda** [comment]
All right, let's not worry about that at the moment. Just make the code ready for review :).

**Comment by kammerer** [comment]
I did some cleanup. It has a few weak spots but I think that can be addressed later.

**Comment by Nuanda** [comment]
Well, it's a big PR, and therefore quite difficult to review. Some form stuff is rather repetitive, but in overall, this is an early showcase and we will probably introduce some changes later on, so no need to have everything right this first time.

Be careful when merging with current controllers (PP, PL) index actions.

Final comment: I do appreciate the interesting humor of submissions_spec.rb, but please change it before merging. Esp. Polish string constants ;).

**Comment by Nuanda** [comment]
:+1:

**Comment by kammerer** [comment]
I have decided to reuse `PlantLine#grid_data` for autocomplete functionality in order to not add more code responsible for very similar things. However now I am not sure about naming. What do you think?

**Comment by Nuanda** [comment]
This is good idea - I already thought about changing that name into sth. else. Either change that name or decompose further and develop a better-named scope for autocomplete. But you may do this in another PR, this one is ripe for merging :).

:+1:

**Pull request merged**
