### PR TITLE
Capistrano deployment

### PR DESCRIPTION
**Pull request by kammerer**
Capistrano configuration is ready as well as deployment server environment. Deployment however will not be possible until repository access from the server is not allowed (thus not ready for review).

Important: it is required to update SSH config on developer's box (see internal wiki).

### CODE REVIEW

**Comment by Nuanda** [comment]
Anyway it looks ok, so :+1: Please merge when TGAC opens the outgoing ssh traffic to the repo server.

**Comment by kammerer** [comment]
@Nuanda please, pull latest changes and try `bin/cap production deploy`

**Comment by Nuanda** [comment]
@kammerer Sorry for a capistrano newbie question, but when I pick a branch to deploy, does it deploy my state of that branch (with "local" commits) via ssh or does it make the remote deployment pull changes from github's state of that branch (which means all my "local" commits have to be pushed)?

**Comment by kammerer** [comment]
AFAIK it pulls from the repo.

2015-04-28 10:55 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> @kammerer <https://github.com/kammerer> Sorry for a capistrano newbie
> question, but when I pick a branch to deploy, does it deploy my state of
> that branch (with "local" commits) via ssh or does it make the remote
> deployment pull changes from github's state of that branch (which means all
> my "local" commits have to be pushed)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/168#issuecomment-96981408>.
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
Anyway, it works. Please merge.

**Pull request merged**
