### PR TITLE
Added foreign key declarations and purged obsolete field in trait_scores

### LINKED ISSUE #317: Add foreign key declarations in BIP model to guard against data inconsistency
See http://edgeguides.rubyonrails.org/4_2_release_notes.html#foreign-key-support

### PR DESCRIPTION
**Pull request by nowakowski**
Fixes #317

### CODE REVIEW

**Comment by nowakowski** [comment]
**Caution** This operation is somewhat premature as long as issue #314 remains open. For the time being I have set the most liberal enforcement rules possible for all FKs (set null on delete, cascade on update). Any relation classified as mandatory in #314 will at least need to have its associated deletion rule upgraded to :cascade (or possibly :restrict -- requiring further changes in `spec/models/model_spec.rb`).

**Comment by Nuanda** [comment]
I rather think :restrict, but we will deal with that later, when we add relation existence requirement.

I understand that all these FKs allow to set nil value, and they set nil for related_id values when the related resource is being destroyed?

**Comment by nowakowski** [comment]
Yes, that's the meaning of `:nullify`.

**Comment by Nuanda** [comment]
:+1:

**Pull request merged**
