### PR TITLE
ES setup for five 'locus' CS model classes

### PR DESCRIPTION
**Pull request by Nuanda**
Tomasz, I did five further models. After you review that PR I will add all other models directly to master.

### CODE REVIEW

**Comment by Nuanda** [comment]
Couldn't resists after I saw this: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_associations.rb :). Provided we index all visible table columns and visible relations, the automatic json structure generator should work in most cases. In other cases (PP, LM, MA) one may redefine the structure.

**Comment by Nuanda** [comment]
However, I've got a problem with travis stubbornly failing one of my tests (which work ok on my local machine).

**Comment by Nuanda** [comment]
That is very strange - looks like Travis gets MapLocusHit model file from master, instead of this branch. What gives?..

**Comment by Nuanda** [comment]
Ok, @kammerer sorry for a lot of spam. Still not sure what I'm doing wrong but please review it anyway - I'll sort the travis problem later, if it persists after master merge.

**Comment by kammerer** [comment]
:+1:

**Comment by kammerer** [comment]
I forgot one minor issue - new models should be added to `config/deploy.rb` to make sure indices are rebuild on deploy (also, if it takes to much time this code should be tweaked to rebuild only when necessary).

**Comment by Nuanda** [comment]
Should those indices be built in same specific order?

**Comment by kammerer** [comment]
It does not matter I think.

2015-05-11 18:35 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Should those indices be built in same specific order?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/254#issuecomment-100973097>
> .
>



-- 
Tomasz Szymczyszyn

**Pull request merged**
