### PR TITLE
Fixes in search

### PR DESCRIPTION
**Pull request by Nuanda**
Several updates to ES indexing, some small fixes.

### CODE REVIEW

**Comment by Nuanda** [comment]
@kammerer Tomasz, I made a few changes to ES indices - some because the structure of browse section data tables changed (and it only makes sense to search through what is visible to the user), and some are related to the issues (?) detected this morning.

Please review.

One more thing remains - TS table is not indexed right now. It's a lot of data yet I think we should do that, at least give it a try (and see what kind of delays/mem consumption we have).

**Comment by kammerer** [comment]
What ES version are you using?

**Comment by kammerer** [comment]
Looks good :+1:

**Comment by Nuanda** [comment]
2.3.3

**Comment by kammerer** [comment]
@Nuanda We use 1.5 in production...

**Comment by Nuanda** [comment]
I know, my OS upgrade did it to me (I use system-provided ES). So I deployed and tested it a second ago, on production, and it looks like MP.map_position works as intended (only full matches are honored).

**Pull request merged**
