### PR TITLE
Trait scores datatable

### LINKED ISSUE #152: In PP table_columns make fpl called by its full name
Otherwise it tricks the datatables view to call that column simply plant line, since it does not know its the female parent line.

### PR DESCRIPTION
**Pull request by Nuanda**
Apart from adding TraitScores table it also provides a special handling for tables where records are grouped (no Annotable metadata should be presented there) and fixes one important Filterable issue.

Fixes #152

### CODE REVIEW

**Comment by Nuanda** [comment]
The code duplication in Filterable and Pluckable was noted, and will be dealt with later, #144

**Comment by Nuanda** [comment]
Sorry, not RFR yet.

**Comment by Nuanda** [comment]
All right, RFR now.

**Comment by kammerer** [comment]
:+1:

**Pull request merged**
