### PR TITLE
Fixed margins for action buttons in submissions table

### LINKED ISSUE #482: Fix margins for action buttons in submissions table
See: https://github.com/eSpectrum-IT/brassica/pull/480#issue-149869481

### PR DESCRIPTION
**Pull request by kammerer**
Fixes #482

### CODE REVIEW

**Comment by Nuanda** [comment]
Confirmed in FF and Chromium. Can you check it in the IE?

Also, what does the new replace library doing? Can I use it to redefine the style for an 'externally defined' css class?

**Comment by kammerer** [comment]
I will check IE. 

Replace works just like Bootstrap's Collapse but it does not modify dimensions, so right now it just changes display property of affected elements.

**Comment by Nuanda** [comment]
Ah, I didn't scroll it down till the end - I see it's just a different class there.

**Comment by Nuanda** [comment]
It's :+1: if it works in IE.

**Comment by kammerer** [comment]
Works in IE11 at least.

**Pull request merged**
