### PR TITLE
Basic read API documentation structure

### PR DESCRIPTION
**Pull request by kammerer**
See #221

The content itself is still very sketchy I think that there are all important elements included.

### CODE REVIEW

**Comment by Nuanda** [comment]
@kammerer I fixed left-hand-side links to model sections. I also added the container to see how it fits in the target width. Finally, I wrapped some lines - it's easier for me to read, but you may revert that.

**Comment by Nuanda** [comment]
:+1:

**Comment by Nuanda** [comment]
One more thing in case you'd be able to fix it in this PR. When scrolled to the bottom of the page, the left menu gets behind the footer.

**Comment by kammerer** [comment]
I'm not aware of any easy fix for this (probably some JS positioning will be needed), so I'd rather left it for now and wait for the final styling to be done.

**Comment by Nuanda** [comment]
Ok. If my changes are ok, please merge. :+1:

**Pull request merged**
