### PR TITLE
Make more fields required in trial submission

### LINKED ISSUE #501: New set of required form elements of Plant Trial submission
Apart from what is currently required: Year, Place name, Units of measurements (new Trait form).

### PR DESCRIPTION
**Pull request by kammerer**
Fixes #501

### CODE REVIEW

**Comment by Nuanda** [comment]
Can I ask for one more thing: Project name autocomplete hint? There are going to be multiple submissions for a project, and it would be nice to have all trial project names, for the same project, written the same way. Autocomplete helps with this.

**Comment by Nuanda** [comment]
Sorry for stretching that, but it's simpler that way - can you add the following hint for the trial year field:

"Please provide information on the year the trial took place. Note that you can only submit trait data from one year at a time. Examples: 2004, 2005, 2016." (taken from #407)

**Comment by kammerer** [comment]
Sure

2016-05-18 14:01 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Sorry for stretching that, but it's simpler that way - can you add the
> following hint for the trial year field:
>
> "Please provide information on the year the trial took place. Note that
> you can only submit trait data from one year at a time. Examples: 2004,
> 2005, 2016." (taken from #407
> <https://github.com/eSpectrum-IT/brassica/issues/407>)
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/506#issuecomment-220005591>
>



-- 
Tomasz Szymczyszyn

**Comment by kammerer** [comment]
It appears that we do not have regular auto-complete input fields anywhere in BIP. IIRC that's because the select2 library was not really suitable for them. So, I added the same widget that is used in other places for selecting existing or entering new values, hope that is ok.

Also, there was a minor privacy issue with these widgets which I fixed.

**Comment by Nuanda** [comment]
Was Project name required before?

**Comment by Nuanda** [comment]
I added most of the help messages mentioned by @teatree1212 in #407 for the 1st and the 2nd step. The 3rd step will undergo major refactoring anyway.

**Comment by Nuanda** [comment]
Apart from the question of the project name being mandatory, I have another question: are these fields required in API as well (I mean the fields you have added as required in forms)?

**Comment by wjurkowski** [comment]
Yes, please!

2016-05-19 13:09 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by kammerer** [comment]
Tomasz,

1. Yes, project name was required before.
2. No, I haven't touched the API. I will do that now.

**Comment by kammerer** [comment]
I made new fields required in the API too (and updated the docs).

**Comment by Nuanda** [comment]
:+1:

**Pull request merged**
