### PR TITLE
Variable number of submission steps

### LINKED ISSUE #499: Management of subsequent years of plant trials
See #488 for the beginning of this discussion (points 1. and 8.).

@teatree1212 So, my proposition, if not decided otherwise by the experimentalists, is to keep all plant trial submission annual. Therefore we will:
 - keep asking for only a single year in the 1st step of the submission
 - will ask for a single image of a plot overview, reflecting the way it was planted this exact year of the trial
 - obviously, scoring should be from this single year only
 - multi-year trials well end up with several records in the PlantTrial table, one per year.

So, the crucial question, of course, is: are there trait scoring scenarios, esp. for mean data, that average over the time axis? Like - there is a single scoring sheet that has e.g. mean values over three consecutive years? Because submission of such data might be problematic having the above assumptions.

### PR DESCRIPTION
**Pull request by kammerer**
Fixes #499 and related to #502.

- it is now possible to have different number of steps in submissions of different types
- trial layout image upload is extracted into its own step 
- empty placeholder step is added between traits and scoring 

Note that it probably should not be merge to master with this empty step added.

### CODE REVIEW

**Comment by Nuanda** [comment]
I've got my own branch that has almost all needed additions to parser/finalizer (not to forms). Of course, this PR impacts that branch. How do you propose to proceed with merging (after this one is reviewed)?

**Comment by Nuanda** [comment]
@kammerer Tomasz, I tried to update step count for things related to Trial Submission. Please see the changes in case I did something wrong.

One thing that certainly is still wrong is the publishable/published/visibility migration, that needs to be a bit smarter now. I added a TODO there in the code - please try to fix that.

**Comment by kammerer** [comment]
Argh, I see now that PR was somewhat incomplete... I started working on "flattening" submission content, so that instead of `submission.content.step06.data_provenance` we would just call `submission.content.data_provenance`, but then I got doubts and skipped that change. As a result I forgot to update step numbers in many places.

**Comment by kammerer** [comment]
As for the migration - what do you think about removing the data-migration part altogether? I assume it is already deployed, so there is no point in keeping that code forever.

There is another issue that I forgot to mention - the contents of existing submissions will no longer be valid, I mean, they will / would crash the finalizer. We need to decide if we want to migrate them or keep without changes. The latter is OK with me unless there are any "real" trial submissions in progress.

**Comment by Nuanda** [comment]
Ok, we will merge this with master, then. We will simply not deploy it to production before we merge the other branch, and then maybe also with new step 3 form.

All right re. the migration. Also, I don't think there are any real submissions in progress right now. We may, however, double check that with our users before deploying (and then we will destroy the unfinished submissions before we change the code base). Are we talking only trial submissions? Or all submissions?

**Comment by kammerer** [comment]
Only trial submissions.

2016-06-08 22:16 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Ok, we will merge this with master, then. We will simply not deploy it to
> production before we merge the other branch, and then maybe also with new
> step 3 form.
>
> All right re. the migration. Also, I don't think there are any real
> submissions in progress right now. We may, however, double check that with
> our users before deploying (and then we will destroy the unfinished
> submissions before we change the code base). Are we talking only trial
> submissions? Or all submissions?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/pull/536#issuecomment-224714121>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA2yXNiIyojFgboYU0fPPTGOTlIWI0Vks5qJyMogaJpZM4Iwq3Z>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
@kammerer So, it's :+1: from me to merge it with master. If you think the changes I did (regarding renumbering of steps here and there) are ok, please go ahead with the merge.

**Comment by kammerer** [comment]
@Nuanda Your changes are fine, thanks. I am not sure about merging to master right away. Shouldn't we wait for your changes and #538 to be ready? If we merge now, deploying sth else in the meantime will be more difficult (still possible of course).

**Comment by Nuanda** [comment]
I don't mind having that temporary in master. #535 is rather finished and awaits that PR. We may merge this branch to #535 if you prefer that. Then, when finished, I will PR the other branch and we will delete this one after successful merge. Would that be better?

We can work together on #538 inside #535, after we merge this branch here.

**Pull request merged**
