### PR TITLE
Plant trial submission

### LINKED ISSUE #331: PlantTrial submission process base
TODOs in this issue:
 - [x] refactor submission step and content partials and forms so we have different code for different type of submission
 - [x] provide rudimentary dedicated PT submission decorator
 - [x] provide rudimentary dedicated PT submission finalizer
 - [x] refactor all PP submission specs to test PT submission process as well
 - [x] enable submission view to show PT submission tab and allow to start the PT submission process
 - [x] be able to show finalized PT submissions in both my submissions and the front page lists
 - [x] provide general PT submission description and first version of each step contextual help text.

### PR DESCRIPTION
**Pull request by Nuanda**
Fixes #331 #332 #333 #334 #335 #336 #337 #339 #342

### CODE REVIEW

**Comment by Nuanda** [comment]
@kammerer Tomasz, does it fix #340 ?

**Comment by Nuanda** [comment]
BTW I merged it with large writable API update (10 more models). I think this is ready for merge, deploy and testing - what do you think?

**Comment by kammerer** [comment]
It does not fix #340, I will do that one tomorrow.

**Comment by kammerer** [comment]
Generally it looks OK, I think it can be merged.

**Pull request merged**
