### PR TITLE
Add more Search services specs

### LINKED ISSUE #196: Implement pending specs of Search class

### PR DESCRIPTION
**Pull request by kammerer**
Fixes #196 

I am not really sure how many different cases should we test here as there is a multitude of combinations possible. WDYT?

### CODE REVIEW

**Comment by Nuanda** [comment]
Sure. Let's be pragmatic. We want to test searching for numeric values, like in the QTL table (a lot of numbers, but saved as text, sadly :( ). That is, it actually might be better for the search. So make sure this works.

The other case are email values in a current "annotation" field `entered_by_whom` - simply make sure the `at` character works (though I'm not sure we will index that field.

So make these two special cases work.

**Comment by kammerer** [comment]
Added these two cases.

**Comment by Nuanda** [comment]
Please fix the specs. Otherwise :+1:

**Comment by kammerer** [comment]
You mean Travis? Not sure why it failed, now it passes (with the same seed on local too).

**Pull request merged**
